### PR TITLE
Adds more checking options

### PR DESCRIPTION
**Pull request by crowstar**
Converts time to 12hr to allow for more quads checking (e.g. 2311 -> 1111 which is quads)

TODO:
Add test for 12hr clock
~~allow for quads at the end of times eg 21:11:11 is quads.~~

### CODE REVIEW

**Comment by Akeboshiwind** [comment]
Unfortunately this breaks both 22:22 and 00:00 :'(

**Comment by crowstar** [comment]
Yea was going to add something that did max of 12 or 24hr clocks. Is that what we have now?

**Comment by crowstar** [comment]
Lgtm!

**Comment by Akeboshiwind** [comment]
> Lgtm!

Thanks lol

**Pull request merged**
